name: test_flutter_web

packages:
  - core/**
  - features/**
  - .

scripts:
  clean:
    description: Clean all packages.
    exec: flutter clean
    packageFilters:
      flutter: true

  pub_get:
    description: Get dependencies in all packages.
    exec: flutter pub get
    packageFilters:
      flutter: true

  upgrade:
    description: Upgrade dependencies (point to last commit).
    exec: flutter packages upgrade
    packageFilters:
      flutter: true

  analyze:
    description: Analyze all packages.
    exec: flutter analyze .
    packageFilters:
      flutter: true

  l10n:
    description: Generate l10n internationalization files.
    exec: flutter gen-l10n
    packageFilters:
      fileExists: l10n.yaml

  test:
    description: Run tests in all packages.
    run: flutter test --coverage
    exec:
      concurrency: 1
      failFast: true
      noSelect: true
    packageFilters:
      flutter: true
      dirExists:
        - test
