name: dependencies
description: Export 3rd party and core dependencies.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  components:
    path: ../components
  di:
    path: ../di
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_test:
    sdk: flutter
  get_it: ^7.6.4
  go_router: ^12.1.1
  internationalization:
    path: ../internationalization
  mocktail: ^1.0.1
  network:
    path: ../network
  routes:
    path: ../routes
  theme:
    path: ../theme
  very_good_analysis: ^5.1.0
