name: components
description: Reusable widgets along the whole project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dependencies:
    path: ../dependencies
  flutter:
    sdk: flutter
